from flask import send_file
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle,
    Paragraph, Spacer, Image
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from openpyxl import Workbook
import pandas as pd
from data import engine
import io
import matplotlib.pyplot as plt
from datetime import datetime


# ======================================================
# PDF EXPORT
# ======================================================
def export_pdf():

    df = pd.read_sql(
        """
        SELECT material_name, cost_rupees, co2_score, suitability_score
        FROM prediction_history
        ORDER BY id DESC
        LIMIT 5
        """,
        engine
    )

    if df.empty:
        return "No data available"

    avg_co2 = round(df["co2_score"].mean(), 2)
    avg_cost = round(df["cost_rupees"].mean(), 2)

    traditional_co2 = 15
    traditional_cost = 10

    co2_reduction = round(((traditional_co2 - avg_co2) / traditional_co2) * 100, 2)
    cost_saving = round(((traditional_cost - avg_cost) / traditional_cost) * 100, 2)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()

    # Title
    elements.append(Paragraph(
        "<b>EcoPack AI Sustainability Intelligence Report</b>",
        styles["Heading1"]
    ))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(
        f"Generated on: {datetime.now().strftime('%d %B %Y')}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 20))

    # KPI Section
    elements.append(Paragraph("<b>Key Sustainability Metrics</b>", styles["Heading2"]))
    elements.append(Spacer(1, 10))

    kpi_data = [
        ["Average CO2 (kg)", avg_co2],
        ["Average Cost (INR)", f"₹ {avg_cost}"],
        ["CO2 Reduction (%)", f"{co2_reduction} %"],
        ["Cost Saving (%)", f"{cost_saving} %"]
    ]

    kpi_table = Table(kpi_data, colWidths=[250, 150])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.whitesmoke),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('FONTSIZE', (0,0), (-1,-1), 11),
    ]))

    elements.append(kpi_table)
    elements.append(Spacer(1, 25))

    # Recommendation Table
    elements.append(Paragraph("<b>Top Recommended Materials</b>", styles["Heading2"]))
    elements.append(Spacer(1, 10))

    df_display = df.round(2)
    table_data = [list(df_display.columns)] + df_display.values.tolist()

    table = Table(table_data)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.green),
        ('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('ALIGN',(1,1),(-1,-1),'CENTER'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 30))

    # Cost Chart
    plt.figure()
    plt.bar(df["material_name"], df["cost_rupees"])
    plt.title("Cost Comparison")
    plt.xticks(rotation=45)

    cost_chart = io.BytesIO()
    plt.tight_layout()
    plt.savefig(cost_chart, format='png')
    plt.close()
    cost_chart.seek(0)

    elements.append(Paragraph("<b>Cost Comparison</b>", styles["Heading2"]))
    elements.append(Image(cost_chart, width=5.5*inch, height=3*inch))
    elements.append(Spacer(1, 25))

    # CO2 Chart
    plt.figure()
    plt.bar(df["material_name"], df["co2_score"])
    plt.title("CO2 Comparison")
    plt.xticks(rotation=45)

    co2_chart = io.BytesIO()
    plt.tight_layout()
    plt.savefig(co2_chart, format='png')
    plt.close()
    co2_chart.seek(0)

    elements.append(Paragraph("<b>CO2 Comparison</b>", styles["Heading2"]))
    elements.append(Image(co2_chart, width=5.5*inch, height=3*inch))
    elements.append(Spacer(1, 30))

    elements.append(Paragraph(
        "Report generated by EcoPack AI System.",
        styles["Normal"]
    ))

    doc.build(elements)
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="EcoPack_AI_Report.pdf",
        mimetype='application/pdf'
    )


# ======================================================
# EXCEL EXPORT
# ======================================================
def export_excel():

    df = pd.read_sql(
        """
        SELECT material_name, cost_rupees, co2_score, suitability_score
        FROM prediction_history
        ORDER BY id DESC
        LIMIT 5
        """,
        engine
    )

    if df.empty:
        return "No data available"

    output = io.BytesIO()
    wb = Workbook()
    ws = wb.active
    ws.title = "Top Recommendations"

    ws.append(list(df.columns))

    for row in df.values.tolist():
        ws.append(row)

    wb.save(output)
    output.seek(0)

    return send_file(
        output,
        as_attachment=True,
        download_name="EcoPack_AI_Report.xlsx",
        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
