# export_utils.py

import io
from datetime import datetime
from flask import send_file, jsonify
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from openpyxl import Workbook
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pytz import timezone
import pandas as pd
import analytics


# ======================================================
# PDF EXPORT
# ======================================================
def export_pdf():

    if analytics.LAST_RANKINGS is None or analytics.LAST_RANKINGS.empty:
        return jsonify({"error": "No ranking data available to export"}), 404

    # IMPORTANT → copy + take only TOP 5
    df = analytics.LAST_RANKINGS.copy().head(5)

    # SAFE NUMERIC CONVERSION
    df["co2_score"] = pd.to_numeric(df["co2_score"], errors="coerce").fillna(0)
    df["cost_rupees"] = pd.to_numeric(df["cost_rupees"], errors="coerce").fillna(0)
    df["final_score"] = pd.to_numeric(df["final_score"], errors="coerce").fillna(0)

    # KPI
    avg_co2 = round(df["co2_score"].mean(), 2)
    avg_cost = round(df["cost_rupees"].mean(), 2)

    traditional_co2 = 15
    traditional_cost = 10

    co2_reduction = round(((traditional_co2 - avg_co2) / traditional_co2) * 100, 2)
    cost_saving = round(((traditional_cost - avg_cost) / traditional_cost) * 100, 2)

    # PDF Setup
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )

    elements = []
    styles = getSampleStyleSheet()

    elements.append(Paragraph("<b>EcoPack AI - Sustainability Report</b>", styles["Heading1"]))
    elements.append(Spacer(1, 6))

    elements.append(
        Paragraph(
            f"Generated on: {datetime.now(timezone('Asia/Kolkata')).strftime('%d %B %Y %H:%M')}",
            styles["Normal"]
        )
    )
    elements.append(Spacer(1, 12))

    # KPI Table
    kpi_data = [
        ["Avg CO2 (kg)", avg_co2, "Avg Cost (₹)", avg_cost],
        ["CO2 Reduction (%)", f"{co2_reduction} %", "Cost Saving (%)", f"{cost_saving} %"]
    ]

    kpi_table = Table(kpi_data, colWidths=[120, 80, 140, 80])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (1, 0), (-1, -1), 'CENTER')
    ]))

    elements.append(kpi_table)
    elements.append(Spacer(1, 15))

    # Recommendation Table
    elements.append(Paragraph("<b>Top 5 Recommended Materials</b>", styles["Heading3"]))
    elements.append(Spacer(1, 6))

    df_display = df[["rank", "material_name", "cost_rupees", "co2_score", "final_score"]].round(2)
    table_data = [list(df_display.columns)] + df_display.values.tolist()

    recommendation_table = Table(table_data, repeatRows=1)
    recommendation_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.green),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('ALIGN', (2, 1), (-1, -1), 'CENTER')
    ]))

    elements.append(recommendation_table)
    elements.append(Spacer(1, 15))

    # COST CHART
    fig1, ax1 = plt.subplots(figsize=(3, 2.2))
    ax1.bar(df["material_name"], df["cost_rupees"])
    ax1.set_title("Cost Comparison", fontsize=8)
    ax1.tick_params(axis='x', rotation=45, labelsize=6)
    ax1.tick_params(axis='y', labelsize=6)
    cost_chart = io.BytesIO()
    plt.tight_layout()
    plt.savefig(cost_chart, format='png')
    plt.close(fig1)
    cost_chart.seek(0)

    # CO2 CHART
    fig2, ax2 = plt.subplots(figsize=(3, 2.2))
    ax2.bar(df["material_name"], df["co2_score"])
    ax2.set_title("CO2 Comparison", fontsize=8)
    ax2.tick_params(axis='x', rotation=45, labelsize=6)
    ax2.tick_params(axis='y', labelsize=6)
    co2_chart = io.BytesIO()
    plt.tight_layout()
    plt.savefig(co2_chart, format='png')
    plt.close(fig2)
    co2_chart.seek(0)

    img1 = Image(cost_chart, width=2.8 * inch, height=2.2 * inch)
    img2 = Image(co2_chart, width=2.8 * inch, height=2.2 * inch)

    chart_table = Table([[img1, img2]], colWidths=[3 * inch, 3 * inch])
    chart_table.setStyle(TableStyle([('ALIGN', (0, 0), (-1, -1), 'CENTER')]))

    elements.append(chart_table)
    elements.append(Spacer(1, 12))
    elements.append(Paragraph("Generated by EcoPack AI System", styles["Normal"]))

    doc.build(elements)
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="EcoPack_AI_Report.pdf",
        mimetype='application/pdf'
    )


# ======================================================
# EXCEL EXPORT
# ======================================================
def export_excel():

    if analytics.LAST_RANKINGS is None or analytics.LAST_RANKINGS.empty:
        return jsonify({"error": "No ranking data available to export"}), 404

    df = analytics.LAST_RANKINGS.copy().head(5)

    output = io.BytesIO()
    wb = Workbook()
    ws = wb.active
    ws.title = "Top Recommendations"

    ws.append(list(df.columns))

    for row in df.values.tolist():
        ws.append(row)

    wb.save(output)
    output.seek(0)

    return send_file(
        output,
        as_attachment=True,
        download_name="EcoPack_AI_Report.xlsx",
        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )